# Generated by Django 4.0.4 on 2022-05-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0002_profile_repo_remove_employer_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='repos',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='user',
        ),
    ]
