# Generated by Django 4.0.4 on 2022-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0003_remove_profile_owner_remove_profile_repos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.CharField(max_length=50),
        ),
    ]
